name: Deploy Streamlit app to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit
          pip install scikit-learn

      - name: Build Streamlit app
        run: |
          mkdir build
          streamlit run StartUp.py --server.enableCORS false --server.enableXsrfProtection false &
          sleep 10
          wget -r -p -k http://localhost:8501
          mv localhost:8501 build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
